### ISSUE TITLE
User login with correct login data returns wrong password error

### ISSUE THREAD

**Issue by MarkBorca** [Austreelis/devII_2TL1-5#27]
- error at login, wrong password

**Comment by Austreelis** [comment]
If you could include a way to reliably reproduce the error, as well as the stack trace (I think I pretty much see the stack trace it should output, but I just wanna make sure).

**Comment by Austreelis** [comment]
second thought on this though: ehat about we just drop password checking ? Just give the `Session` a user login, error if it doesn't exist in the db but allow login without checking password. That would be the easy quick fix.
